"""Generate the version-controlled Managed Agents control-plane files.

Writes, under ``cma/``:
  - environment.yaml               the cloud environment
  - <role>.agent.yaml              one agent per role (tools embedded)
  - seed/<adjuster>.md             seed content for adjuster memory stores
  - setup.sh                       applies the above via the `ant` CLI and
                                   provisions + seeds the memory stores, then
                                   writes ../data/cma_config.json

The agent YAML (name/model/system/tools) is generated from the same
`cma`/`roles`/`agent_schemas` code the runtime uses, so the checked-in control
plane never drifts from the tool set. Re-run this whenever the tools or role
allow-lists change:  python3 gen_cma_yaml.py

Applying is the `ant` control-plane flow (see shared/anthropic-cli.md):
    cd cma && ./setup.sh
"""

import json
import stat
from pathlib import Path

import yaml

import cma
from roles import Role

OUT_DIR = Path(__file__).with_name("cma")
SEED_DIR = OUT_DIR / "seed"


def _str_representer(dumper: yaml.Dumper, data: str):
    # Use a block literal for multi-line strings (system prompts) so they stay readable.
    style = "|" if "\n" in data else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style=style)


yaml.add_representer(str, _str_representer)


def _dump(obj: dict) -> str:
    # width huge so long descriptions are never line-wrapped (which would fold to spaces).
    return yaml.dump(obj, sort_keys=False, default_flow_style=False, width=10**9, allow_unicode=True)


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _environment_body() -> dict:
    return {
        "name": "insurance-mock-env",
        "config": {"type": "cloud", "networking": {"type": "unrestricted"}},
    }


def _agent_body(role: Role) -> dict:
    return {
        "name": f"insurance-{role.value}",
        # Per-role, matching what `cma.setup()` sends at agent-create time
        # (cma.py:209) — a single `cma.MODEL` no longer exists.
        "model": cma.MODEL_BY_ROLE[role],
        "system": cma._agent_system(role),
        "tools": cma.agent_tools_for_role(role),
    }


def _setup_script() -> str:
    # Bash lines built from cma.MEMORY_ADJUSTERS so the script matches the runtime config.
    store_creates = []
    config_stores = []
    for adjuster_id in cma.MEMORY_ADJUSTERS:
        var = f"MS_{adjuster_id.upper()}"
        name = cma._memory_store_name(adjuster_id)
        seed = cma._SEED_MEMORY.get(adjuster_id)
        block = [
            f'{var}=$(ant beta:memory-stores create \\',
            f'  --name "{name}" \\',
            f'  --description "Personal memory for adjuster {adjuster_id}: auto-approval policy overrides and working notes." \\',
            "  --transform id --raw-output)",
        ]
        if seed:
            block += [
                f'ant beta:memory-stores:memories create \\',
                f'  --memory-store-id "${var}" \\',
                f'  --path "/policies.md" \\',
                f'  --content @seed/{adjuster_id}.md >/dev/null',
            ]
        block.append(f'echo "  memory store {name}: ${var}"')
        store_creates.append("\n".join(block))
        config_stores.append(f'    "{adjuster_id}": "${var}"')

    stores_block = "\n\n".join(store_creates)
    config_stores_json = ",\n".join(config_stores)

    return f'''#!/usr/bin/env bash
# Provision the Managed Agents control plane for the insurance mock via the `ant` CLI.
# Generated by gen_cma_yaml.py — re-run that to regenerate. Run from the cma/ directory:
#     cd cma && ./setup.sh
# Requires `ant` on PATH and an MA-enabled workspace (ant auth login / ANTHROPIC_API_KEY).
set -euo pipefail
cd "$(dirname "$0")"

echo "Creating environment..."
ENV_ID=$(ant beta:environments create < environment.yaml --transform id --raw-output)
echo "  environment: $ENV_ID"

echo "Creating agents..."
ADJUSTER_AGENT=$(ant beta:agents create < adjuster.agent.yaml --transform id --raw-output)
echo "  adjuster agent: $ADJUSTER_AGENT"
INSURER_AGENT=$(ant beta:agents create < insurer.agent.yaml --transform id --raw-output)
echo "  insurer agent:  $INSURER_AGENT"
AGENT_AGENT=$(ant beta:agents create < agent.agent.yaml --transform id --raw-output)
echo "  agent (maintenance): $AGENT_AGENT"

echo "Creating memory stores..."
{stores_block}

echo "Writing ../data/cma_config.json..."
cat > ../data/cma_config.json <<JSON
{{
  "environment_id": "$ENV_ID",
  "agents": {{
    "adjuster": "$ADJUSTER_AGENT",
    "insurer": "$INSURER_AGENT",
    "agent": "$AGENT_AGENT"
  }},
  "memory_stores": {{
{config_stores_json}
  }}
}}
JSON

echo "Done. Run:  python3 ../cma.py"
'''


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    # environment
    env_body = _environment_body()
    _write(OUT_DIR / "environment.yaml", _dump(env_body))
    written = ["environment.yaml"]

    # agents (one per role)
    for role in Role:
        body = _agent_body(role)
        # round-trip check: the YAML must reload to exactly the body we dumped.
        text = _dump(body)
        assert yaml.safe_load(text) == body, f"YAML round-trip mismatch for {role.value}"
        _write(OUT_DIR / f"{role.value}.agent.yaml", text)
        written.append(f"{role.value}.agent.yaml")

    # seed files for adjusters that ship with memory content
    for adjuster_id, content in cma._SEED_MEMORY.items():
        _write(SEED_DIR / f"{adjuster_id}.md", content)
        written.append(f"seed/{adjuster_id}.md")

    # setup.sh (executable)
    setup_path = OUT_DIR / "setup.sh"
    _write(setup_path, _setup_script())
    setup_path.chmod(setup_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    written.append("setup.sh (chmod +x)")

    print("Wrote under cma/:")
    for name in written:
        print(f"  {name}")


if __name__ == "__main__":
    main()
