#!/usr/bin/env bash
# Provision the Managed Agents control plane for the insurance mock via the `ant` CLI.
# Generated by gen_cma_yaml.py — re-run that to regenerate. Run from the cma/ directory:
#     cd cma && ./setup.sh
# Requires `ant` on PATH and an MA-enabled workspace (ant auth login / ANTHROPIC_API_KEY).
set -euo pipefail
cd "$(dirname "$0")"

echo "Creating environment..."
ENV_ID=$(ant beta:environments create < environment.yaml --transform id --raw-output)
echo "  environment: $ENV_ID"

echo "Creating agents..."
ADJUSTER_AGENT=$(ant beta:agents create < adjuster.agent.yaml --transform id --raw-output)
echo "  adjuster agent: $ADJUSTER_AGENT"
INSURER_AGENT=$(ant beta:agents create < insurer.agent.yaml --transform id --raw-output)
echo "  insurer agent:  $INSURER_AGENT"
AGENT_AGENT=$(ant beta:agents create < agent.agent.yaml --transform id --raw-output)
echo "  agent (maintenance): $AGENT_AGENT"

echo "Creating memory stores..."
MS_JAIME=$(ant beta:memory-stores create \
  --name "adjuster-jaime" \
  --description "Personal memory for adjuster jaime: auto-approval policy overrides and working notes." \
  --transform id --raw-output)
ant beta:memory-stores:memories create \
  --memory-store-id "$MS_JAIME" \
  --path "/policies.md" \
  --content @seed/jaime.md >/dev/null
echo "  memory store adjuster-jaime: $MS_JAIME"

MS_SAM=$(ant beta:memory-stores create \
  --name "adjuster-sam" \
  --description "Personal memory for adjuster sam: auto-approval policy overrides and working notes." \
  --transform id --raw-output)
echo "  memory store adjuster-sam: $MS_SAM"

MS_JANE=$(ant beta:memory-stores create \
  --name "adjuster-jane" \
  --description "Personal memory for adjuster jane: auto-approval policy overrides and working notes." \
  --transform id --raw-output)
ant beta:memory-stores:memories create \
  --memory-store-id "$MS_JANE" \
  --path "/policies.md" \
  --content @seed/jane.md >/dev/null
echo "  memory store adjuster-jane: $MS_JANE"

echo "Writing ../data/cma_config.json..."
cat > ../data/cma_config.json <<JSON
{
  "environment_id": "$ENV_ID",
  "agents": {
    "adjuster": "$ADJUSTER_AGENT",
    "insurer": "$INSURER_AGENT",
    "agent": "$AGENT_AGENT"
  },
  "memory_stores": {
    "jaime": "$MS_JAIME",
    "sam": "$MS_SAM",
    "jane": "$MS_JANE"
  }
}
JSON

echo "Done. Run:  python3 ../cma.py"
